### ISSUE TITLE
Failed to minify the code from this file ./node_modules/30-seconds-of-code/dist/_30s.esm.js:2

### ISSUE THREAD

**Issue by sorcer1** [30-seconds/30-seconds-of-code#866]
## Bug description 
After adding the package to my project, i try to build a production build with webpack and i get this message :

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/30-seconds-of-code/dist/_30s.esm.js:2

## Steps to reproduce
Install the package to the project :
`npm install 30-seconds-of-code`

Add the import statement :
`import ThirtySeconds from '30-seconds-of-code'`

Use one function :
`const states = ThirtySeconds.initializeArrayWithRange(5)`

Build with webpack :
`npm run build`

## Expected behavior
A script compiled...

## Environment
ReactJS project

**Comment by wfxphoebus** [comment]
me too

**Comment by atomiks** [comment]
Seems like the package (as of 1.2.2) hasn't been updated with the proper files yet. @Chalarangelo 

Can you go to `node_modules/30-seconds-of-code/dist/_30s.esm.js` and replace it with the code here: https://github.com/30-seconds/30-seconds-of-code/blob/master/dist/_30s.esm.js and see if it compiles?

Note there's no default export with the new files, it's recommended to import it like 

```js
import { initializeArrayWithRange } from '30-seconds-of-code'
```

so webpack can treeshake all the other unused functions so they don't end up in the bundle

**Comment by sorcer1** [comment]
> Seems like the package (as of 1.2.2) hasn't been updated with the proper files yet. @Chalarangelo
> 
> Can you go to `node_modules/30-seconds-of-code/dist/_30s.esm.js` and replace it with the code here: https://github.com/30-seconds/30-seconds-of-code/blob/master/dist/_30s.esm.js and see if it compiles?
> 
> Note there's no default export with the new files, it's recommended to import it like
> 
> ```js
> import { initializeArrayWithRange } from '30-seconds-of-code'
> ```
> 
> so webpack can treeshake all the other unused functions so they don't end up in the bundle

you're right, it's works !

**Comment by wfxphoebus** [comment]
ERROR  Failed to compile with 1 errors                                                                                                    9:35:41 PM

 error  in ./node_modules/30-seconds-of-code/dist/_30s.esm.js

Module parse failed: Unexpected token (730:20)
You may need an appropriate loader to handle this file type.
|   items
|     .filter(item => item[link] === id)
|     .map(item => ({ ...item, children: nest(items, item.id) }));
| const nodeListToArray = nodeList => [...nodeList];
| const none = (arr, fn = Boolean) => !arr.some(fn);

 @ ./src/global.js 13:13-42
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:9527 webpack/hot/dev-server ./src/main.js

URIError: Failed to decode param '/%3C%=htmlWebpackPlugin.options.path%20%%3E/tinymce4.7.5/tinymce.min.js'
    at decodeURIComponent (<anonymous>)
    at decode_param (/Users/Well/Gitlab/fg-view/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/Users/Well/Gitlab/fg-view/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/Users/Well/Gitlab/fg-view/node_modules/express/lib/router/index.js:574:18)
    at next (/Users/Well/Gitlab/fg-view/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/Users/Well/Gitlab/fg-view/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/Well/Gitlab/fg-view/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/Well/Gitlab/fg-view/node_modules/express/lib/router/index.js:317:13)
    at /Users/Well/Gitlab/fg-view/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/Well/Gitlab/fg-view/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/Well/Gitlab/fg-view/node_modules/express/lib/router/index.js:275:10)
    at query (/Users/Well/Gitlab/fg-view/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/Users/Well/Gitlab/fg-view/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/Well/Gitlab/fg-view/node_modules/express/lib/router/index.js:317:13)
    at /Users/Well/Gitlab/fg-view/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/Well/Gitlab/fg-view/node_modules/express/lib/router/index.js:335:12)

**Comment by atomiks** [comment]
@wfxphoebus looks like it's failing because of the object spread operator (`...`), which is a new ES2018 feature.

If you're using Babel 6, install `babel-plugin-transform-object-rest-spread`. Babel 7 handles it automatically.
